### ISSUE TITLE
Unsupported HDF5 version: 1.10.0

### ISSUE THREAD

**Issue by kaismax** [jcjohnson/fast-neural-style#160]
>>th train.lua -h5_file ../out/h5/file.h5 -style_image images/styles/starry_night.jpg -style_image_size 384 -content_weights 1.0 -style_weights 5.0 -gpu 0
 /home/kaismax/torch/install/bin/luajit: /home/kaismax/torch/install/share/lua/5.1/trepl/init.lua:389:  
 /home/kaismax/torch/install/share/lua/5.1/trepl/init.lua:389: /home/kaismax/torch/install/share/lua/5.1 
 /hdf5/ffi.lua:71: **Unsupported HDF5 version: 1.10.0**
i can't solve this problem.. help please ,,
$luarocks list
Installed rocks:
....
 0-0 (installed) - /home/kaismax/torch/install/lib/luarocks/rocks
...

$ th
 
  ______             __   |  Torch7 
 /_  __/__  ________/ /   |  Scientific computing for Lua. 
  / / / _ \/ __/ __/ _ \  |  Type ? for help 
 /_/  \___/_/  \__/_//_/  |  https://github.com/torch 
                          |  http://torch.ch

**Comment by Keloo** [comment]
Did you find any solution? I have the same problem

**Comment by Achhhe** [comment]
the same problem to me

**Comment by emerth** [comment]
I solved this problem by building HDF5 1.8.18 from source and installing it in /opt/hdf5-1.8.18.
> wget https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.18/src/hdf5-1.8.18.tar.gz
> tar -xzvf hdf5-1.8.18.tar.gz
>  cd hdf5-1.8.18
> ./configure --prefix=/opt/hdf5-1.8.18
> make
> make install

Building HDF5 prints an unholy amount of warnings from the compiler!

Then did the following:

> export PATH=/opt/hdf5-1.8.18/bin:$PATH
> export LD_LIBRARY_PATH=/opt/hdf5-1.8.18/lib:$LD_LIBRARY_PATH
> luarocks remove hdf5
> luarocks install hdf5
> pip uninstall h5py
> pip install h5py

You do this because luarocks is invoking HDF5's CC wrapper script named h5cc to run the C compiler and h5cc does the script-foo to link against it's version of the libs. In the output from the "luarocks install hdf5" look for confirmation of the HDF5 location used.

I expect you'll need to export these environment variables each session you run the lua scripts.

TBH I didn't bother digging into the pip reinstall except to note that afterwards the file "/usr/local/lib/python2.7/dist-packages/h5py/version.py" contains this line "api_version_tuple = (1,8)"

train.lua is currently grinding away at a dataset!

**Comment by ef314159** [comment]
This doesn't work. Those commands all appear to run correctly, and my .../h5py/version.py contains the 1.8 API tuple, but train.lua still produces the same error and make_style_dataset.py now crashes with

> Traceback (most recent call last):
  File "scripts/make_style_dataset.py", line 5, in \<module>
    import numpy as np
  File "/home/shivanhunter/.local/lib/python2.7/site-packages/numpy/\_\_init__.py", line 142, in \<module>
    from . import core
  File "/home/shivanhunter/.local/lib/python2.7/site-packages/numpy/core/\_\_init__.py", line 57, in \<module>
    from . import numerictypes as nt
  File "/home/shivanhunter/.local/lib/python2.7/site-packages/numpy/core/numerictypes.py", line 111, in \<module>
    from ._type_aliases import (
  File "/home/shivanhunter/.local/lib/python2.7/site-packages/numpy/core/_type_aliases.py", line 63, in \<module>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
  File "/home/shivanhunter/.local/lib/python2.7/site-packages/numpy/core/_type_aliases.py", line 63, in \<setcomp>
    _concrete_types = {v.type for k, v in _concrete_typeinfo.items()}
AttributeError: 'tuple' object has no attribute 'type'

**Comment by HandsomeDevilv112** [comment]
this got me going immediately
https://github.com/deepmind/torch-hdf5/issues/76#issuecomment-357379520
